sudo: false

env:
  global:
    - PIP_DEPS="numpy cython scipy matplotlib nibabel sharedmem statsmodels nose python-coveralls coverage"

matrix:
  include:
    - os: linux
      env:
         - PYTHON_VERSION=2.7
         - MINICONDA_URL="http://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh"
         - COVERAGE=1
    - os: linux
      env:
         - PYTHON_VERSION=3.5
         - MINICONDA_URL="https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh"

before_install:
  - export MINICONDA=$HOME/miniconda
  - export PATH="$MINICONDA/bin:$PATH"
  - hash -r
  - echo $MINICONDA_URL
  - wget $MINICONDA_URL -O miniconda.sh;
  - bash miniconda.sh -b -f -p $MINICONDA;
  - conda config --set always_yes yes
  - conda update conda
  - conda info -a
  - conda install python=$PYTHON_VERSION
  - pip install $PIP_DEPS


install:
  - python setup.py install
  - pip install codecov
script:
    # Change into an innocuous directory and find tests from installation
    - mkdir for_testing
    - cd for_testing
    - if [ "${COVERAGE}" == "1" ]; then
      cp ../.coveragerc .;
      COVER_ARGS="--with-coverage --cover-package popeye";
      fi
    - nosetests --with-doctest --verbose $COVER_ARGS popeye
after_success:
    - coveralls
    - cocecov
